function [manifest, metadata] = buildStimulusSet(imageIDs, masterImageFolder, masterFeatureTable, outputRoot, stimulusSetName, options)
%BUILDSTIMULUSSET Build a self-contained Adaptive Foraging stimulus set.
%   BUILDSTIMULUSSET(IMAGEIDS, MASTERIMAGEFOLDER, MASTERFEATURETABLE,
%   OUTPUTROOT, STIMULUSSETNAME, OPTIONS) validates requested image IDs,
%   copies selected PNG files, and writes manifest.json and metadata.json.
%   [MANIFEST, METADATA] = BUILDSTIMULUSSET(...) also returns the generated
%   structures in-memory for inspection and debugging.
%
%   Required inputs:
%   - imageIDs: numeric vector of requested image IDs.
%   - masterImageFolder: folder containing PNG files named ID_<ID>.png.
%   - masterFeatureTable: MATLAB table with one row per source image.
%   - outputRoot: destination root folder (for example, stimuli/).
%   - stimulusSetName: destination stimulus set folder name.
%
%   Optional OPTIONS fields:
%   - idColumn (default "ID")
%   - displayName (default stimulusSetName)
%   - description (default autogenerated)
%   - version (default "1.0")
%   - overwrite (default false)

    if nargin < 5
        error('buildStimulusSet:MissingInputs', ...
            'At least 5 inputs are required: imageIDs, masterImageFolder, masterFeatureTable, outputRoot, stimulusSetName.');
    end
    if nargin < 6 || isempty(options)
        options = struct();
    end

    options = localNormalizeOptions(options, stimulusSetName);

    localValidateInputs(imageIDs, masterImageFolder, masterFeatureTable, outputRoot, stimulusSetName, options);

    requestedIDs = double(imageIDs(:));
    idValues = localNormalizeIDValues(masterFeatureTable.(options.idColumn), options.idColumn);

    if numel(unique(requestedIDs)) ~= numel(requestedIDs)
        error('buildStimulusSet:DuplicateRequestedIDs', ...
            'imageIDs contains duplicates. Requested IDs must be unique.');
    end

    rowIndexByRequest = zeros(numel(requestedIDs), 1);
    for i = 1:numel(requestedIDs)
        id = requestedIDs(i);
        matchIdx = find(idValues == id);
        if isempty(matchIdx)
            error('buildStimulusSet:MissingIDInTable', ...
                'Requested image ID %g is not present in masterFeatureTable column %s.', id, options.idColumn);
        end
        if numel(matchIdx) > 1
            error('buildStimulusSet:DuplicateIDInTable', ...
                'Requested image ID %g appears %d times in masterFeatureTable column %s; expected exactly one row.', ...
                id, numel(matchIdx), options.idColumn);
        end
        rowIndexByRequest(i) = matchIdx;
    end

    fileNames = strings(numel(requestedIDs), 1);
    sourceFiles = strings(numel(requestedIDs), 1);
    for i = 1:numel(requestedIDs)
        token = localIDToken(requestedIDs(i));
        fileName = "ID_" + token + ".png";
        sourcePath = fullfile(masterImageFolder, fileName);
        if ~isfile(sourcePath)
            error('buildStimulusSet:MissingImageFile', ...
                'PNG file for ID %g was not found at %s.', requestedIDs(i), sourcePath);
        end
        fileNames(i) = fileName;
        sourceFiles(i) = string(sourcePath);
    end

    setFolder = fullfile(char(outputRoot), char(stimulusSetName));
    imagesFolder = fullfile(setFolder, 'images');
    manifestPath = fullfile(setFolder, 'manifest.json');
    metadataPath = fullfile(setFolder, 'metadata.json');

    if isfolder(setFolder)
        if ~options.overwrite
            error('buildStimulusSet:OutputExists', ...
                'Output folder already exists: %s. Set options.overwrite=true to replace it.', setFolder);
        end
    end

    selected = masterFeatureTable(rowIndexByRequest, :);
    featureNames = selected.Properties.VariableNames;
    featureNames(strcmp(featureNames, options.idColumn)) = [];

    metadata = localBuildMetadata(selected, requestedIDs, fileNames, featureNames);
    featureSchema = localBuildFeatureSchema(masterFeatureTable, featureNames);

    manifest = struct();
    manifest.name = char(stimulusSetName);
    manifest.displayName = char(options.displayName);
    manifest.description = char(options.description);
    manifest.version = char(options.version);
    manifest.imageDirectory = 'images';
    manifest.metadataFile = 'metadata.json';
    manifest.features = featureSchema;

    % All validation is complete; start writing output.
    if options.overwrite && isfolder(setFolder)
        rmdir(setFolder, 's');
    end

    if ~isfolder(char(outputRoot))
        mkdir(char(outputRoot));
    end
    mkdir(setFolder);
    mkdir(imagesFolder);

    for i = 1:numel(sourceFiles)
        destination = fullfile(imagesFolder, char(fileNames(i)));
        copied = copyfile(char(sourceFiles(i)), destination);
        if ~copied
            error('buildStimulusSet:CopyFailed', ...
                'Failed to copy %s to %s.', sourceFiles(i), destination);
        end
    end

    localWriteJson(metadataPath, metadata);
    localWriteJson(manifestPath, manifest);

    fprintf('\nAdaptive Foraging stimulus set created successfully.\n');
    fprintf('  Stimulus set: %s\n', stimulusSetName);
    fprintf('  Images copied: %d\n', numel(sourceFiles));
    fprintf('  Metadata rows: %d\n', numel(metadata));
    fprintf('  Features exported: %d\n', numel(featureSchema));
    fprintf('  Output folder: %s\n\n', setFolder);
end

function options = localNormalizeOptions(options, stimulusSetName)
    if ~isstruct(options)
        error('buildStimulusSet:InvalidOptions', 'options must be a struct.');
    end

    options.idColumn = localOptionString(options, 'idColumn', "ID");
    options.displayName = localOptionString(options, 'displayName', string(stimulusSetName));
    options.description = localOptionString(options, 'description', ...
        "Stimulus set generated by buildStimulusSet.");
    options.version = localOptionString(options, 'version', "1.0");

    if isfield(options, 'overwrite')
        options.overwrite = logical(options.overwrite);
        if ~isscalar(options.overwrite)
            error('buildStimulusSet:InvalidOverwrite', 'options.overwrite must be a scalar logical value.');
        end
    else
        options.overwrite = false;
    end
end

function value = localOptionString(options, fieldName, defaultValue)
    if ~isfield(options, fieldName) || isempty(options.(fieldName))
        value = string(defaultValue);
        return;
    end
    v = options.(fieldName);
    if ~(ischar(v) || isstring(v))
        error('buildStimulusSet:InvalidOptionType', ...
            'options.%s must be char or string.', fieldName);
    end
    v = string(v);
    if strlength(v) == 0
        error('buildStimulusSet:EmptyOption', 'options.%s must not be empty.', fieldName);
    end
    value = v;
end

function localValidateInputs(imageIDs, masterImageFolder, masterFeatureTable, outputRoot, stimulusSetName, options)
    if ~(isnumeric(imageIDs) || islogical(imageIDs))
        error('buildStimulusSet:InvalidImageIDs', 'imageIDs must be a numeric vector.');
    end
    if ~isvector(imageIDs) || isempty(imageIDs)
        error('buildStimulusSet:InvalidImageIDs', 'imageIDs must be a non-empty numeric vector.');
    end
    if any(~isfinite(double(imageIDs(:))))
        error('buildStimulusSet:InvalidImageIDs', 'imageIDs must contain only finite numeric values.');
    end

    if ~(ischar(masterImageFolder) || isstring(masterImageFolder))
        error('buildStimulusSet:InvalidMasterImageFolder', ...
            'masterImageFolder must be a char or string path.');
    end
    masterImageFolder = char(masterImageFolder);
    if ~isfolder(masterImageFolder)
        error('buildStimulusSet:MasterImageFolderNotFound', ...
            'masterImageFolder does not exist: %s', masterImageFolder);
    end

    if ~istable(masterFeatureTable)
        error('buildStimulusSet:InvalidFeatureTable', 'masterFeatureTable must be a MATLAB table.');
    end

    if ~(ischar(outputRoot) || isstring(outputRoot))
        error('buildStimulusSet:InvalidOutputRoot', 'outputRoot must be a char or string path.');
    end

    if ~(ischar(stimulusSetName) || isstring(stimulusSetName))
        error('buildStimulusSet:InvalidStimulusSetName', ...
            'stimulusSetName must be a char or string.');
    end
    if strlength(string(stimulusSetName)) == 0
        error('buildStimulusSet:InvalidStimulusSetName', 'stimulusSetName must not be empty.');
    end

    variableNames = masterFeatureTable.Properties.VariableNames;
    if ~any(strcmp(variableNames, char(options.idColumn)))
        error('buildStimulusSet:MissingIDColumn', ...
            'ID column %s was not found in masterFeatureTable.', options.idColumn);
    end
end

function idValues = localNormalizeIDValues(columnData, idColumnName)
    if isnumeric(columnData) || islogical(columnData)
        idValues = double(columnData(:));
        return;
    end

    if isstring(columnData)
        raw = str2double(columnData(:));
    elseif iscategorical(columnData)
        raw = str2double(string(columnData(:)));
    elseif iscellstr(columnData)
        raw = str2double(string(columnData(:)));
    elseif ischar(columnData)
        raw = str2double(string(cellstr(columnData)));
    else
        error('buildStimulusSet:UnsupportedIDColumnType', ...
            'ID column %s must be numeric, logical, string, char, or categorical.', idColumnName);
    end

    if any(isnan(raw))
        error('buildStimulusSet:InvalidIDColumnValues', ...
            'ID column %s contains values that cannot be converted to numeric IDs.', idColumnName);
    end
    idValues = raw;
end

function metadata = localBuildMetadata(selected, requestedIDs, fileNames, featureNames)
    n = numel(requestedIDs);
    emptyFeatures = struct();
    for j = 1:numel(featureNames)
        emptyFeatures.(featureNames{j}) = [];
    end

    metadata = repmat(struct( ...
        'id', 0, ...
        'display', '', ...
        'image', '', ...
        'features', emptyFeatures), n, 1);

    for i = 1:n
        id = requestedIDs(i);
        metadata(i).id = id;
        metadata(i).display = ['ID_' localIDToken(id)];
        metadata(i).image = ['images/' char(fileNames(i))];

        featureStruct = struct();
        for j = 1:numel(featureNames)
            featureName = featureNames{j};
            rawValue = selected.(featureName)(i);
            featureStruct.(featureName) = localJsonSafeValue(rawValue);
        end
        metadata(i).features = featureStruct;
    end
end

function featureSchema = localBuildFeatureSchema(selected, featureNames)
    featureSchema = cell(numel(featureNames), 1);

    for j = 1:numel(featureNames)
        featureName = featureNames{j};
        columnData = selected.(featureName);

        schema = struct();
        schema.name = featureName;
        schema.displayName = featureName;

        if islogical(columnData)
            schema.type = 'boolean';
        elseif isnumeric(columnData)
            if localIsNumericBooleanColumn(columnData)
                schema.type = 'boolean';
            else
                schema.type = 'continuous';
            end
        elseif isstring(columnData) || iscategorical(columnData) || iscellstr(columnData) || ischar(columnData)
            schema.type = 'categorical';
        else
            schema.type = 'categorical';
        end

        featureSchema{j} = schema;
    end
end

function tf = localIsNumericBooleanColumn(columnData)
    values = double(columnData(:));
    values = values(isfinite(values));

    if isempty(values)
        tf = false;
        return;
    end

    uniqueValues = unique(values);
    tf = all(uniqueValues == 0 | uniqueValues == 1);
end

function out = localJsonSafeValue(value)
    % Convert MATLAB values into JSON-safe scalar values.
    if iscell(value)
        if isempty(value)
            out = [];
            return;
        end
        if numel(value) == 1
            out = localJsonSafeValue(value{1});
            return;
        end
        out = cellfun(@localJsonSafeValue, value, 'UniformOutput', false);
        return;
    end

    if isstring(value)
        if isempty(value) || all(ismissing(value))
            out = [];
            return;
        end
        if numel(value) == 1
            out = char(value);
        else
            out = cellstr(value);
        end
        return;
    end

    if ischar(value)
        out = char(value);
        return;
    end

    if iscategorical(value)
        if any(isundefined(value))
            out = [];
            return;
        end
        if numel(value) == 1
            out = char(string(value));
        else
            out = cellstr(string(value));
        end
        return;
    end

    if islogical(value)
        if isempty(value)
            out = [];
            return;
        end
        if isscalar(value)
            out = logical(value);
        else
            out = logical(value);
        end
        return;
    end

    if isnumeric(value)
        if isempty(value)
            out = [];
            return;
        end
        if isscalar(value)
            if isfinite(value)
                out = value;
            else
                out = [];
            end
        else
            value(~isfinite(value)) = NaN;
            out = value;
        end
        return;
    end

    if isdatetime(value) || isduration(value)
        if isempty(value) || any(ismissing(value))
            out = [];
        else
            out = char(string(value));
        end
        return;
    end

    converted = string(value);
    if ismissing(converted) || strlength(converted) == 0
        out = [];
    else
        out = char(converted);
    end
end

function token = localIDToken(id)
    if abs(id - round(id)) < eps(max(1, abs(id)))
        token = sprintf('%d', round(id));
    else
        token = sprintf('%.15g', id);
    end
end

function localWriteJson(filePath, data)
    try
        jsonText = jsonencode(data, 'PrettyPrint', true);
    catch
        jsonText = jsonencode(data);
    end

    fid = fopen(filePath, 'w');
    if fid < 0
        error('buildStimulusSet:FileWriteFailed', 'Unable to open file for writing: %s', filePath);
    end
    cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>
    fprintf(fid, '%s\n', jsonText);
end
